name: Django Deployment Workflow

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run linting
      run: |
        # pip install flake8
        # flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    
    - name: Run tests
      run: |
        python controlbackend/manage.py test
    
    - name: Security checks
      run: |
        # pip install bandit
        bandit -r . -f custom
    
    - name: Deploy to production
      run: |
        # Copy project to destination directory
        sudo rsync -avz ${{ github.workspace }}/ ${{ secrets.SERVER_USER }}.@${{ secrets.SERVER_HOST }}/var/www/djangoproject/
        
        # Set correct permissions
        sudo chown -R www-data:www-data /var/www/djangoproject
        
        # Activate virtual environment (adjust path as needed)
        source /var/www/djangoproject/venv/bin/activate
        
        # Run migrations
        python manage.py migrate
        
        # Collect static files
        python manage.py collectstatic --noinput
        
        # Restart Gunicorn
        sudo systemctl restart gunicorn
        
        # Restart Nginx
        sudo systemctl restart nginx